pub const MAX_FRAMES: u32 = 2;
pub const NUM_COMMAND_BUFFERS_PER_THREAD: u32 = 3;
pub const NUM_SECONDARY_COMMAND_BUFFERS_PER_THREAD: u32 = 2;

pub const MAX_DESCRIPTORS_PER_SET: u32 = 16;
pub const MAX_SHADER_BINDING_INDEX: u32 = 255;
pub const MAX_NUM_BINDLESS_RESOURCECS: u32 = 1024;

pub const BINDLESS_SET_SAMPLED_IMAGE_INDEX: u32 = 10;
pub const BINDLESS_SET_STORAGE_IMAGE_INDEX: u32 = 11;

pub const GLOBAL_DESCRIPTOR_POOL_MAX_SETS: u32 = 2048;
pub const GLOBAL_DESCRIPTOR_POOL_ELEMENT_SIZE: u32 = 128;

pub const INVALID_BINDLESS_TEXTURE_INDEX: u32 = u32::MAX;
